os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "stable"
  - "unstable"


install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i 

before_install:
  - npm install -g npm@latest
  - npm install -g node-gyp
  - rm -rf ~/.node-gyp/

script:
  - npm run-script test-travis

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls

